title               : "Pelatihan"
url                 : "https://dapoerela85.github.io/pelatihan/"
baseurl             : "/pelatihan/"
permalink           : pretty

include:
  - _pages

defaults:
  - scope:
      path: "_posts/**"
      type: posts
    values:
      layout: post
      permalink: /product/:title/
  - scope:
      path: "_pages"
      type: "pages"
    values:
      layout: page
